# fly.toml app configuration file generated for ferrum-tools-server-side on 2023-10-23T00:26:43+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ferrum-tools-server-side"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
